/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package softwareproject;

/**
 *
 * @author omarm
 */
public class admin_home extends javax.swing.JFrame {

    /**
     * Creates new form admin_home
     */
    public admin_home() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        members = new javax.swing.JMenu();
        add_member = new javax.swing.JMenuItem();
        delete_member = new javax.swing.JMenuItem();
        view_members = new javax.swing.JMenuItem();
        trainers = new javax.swing.JMenu();
        add_trainer = new javax.swing.JMenuItem();
        delete_trainer = new javax.swing.JMenuItem();
        view_trainers = new javax.swing.JMenuItem();
        logout = new javax.swing.JMenu();
        exit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 168, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1920, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 954, Short.MAX_VALUE)
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/admin_avatar.png"))); // NOI18N
        jMenu1.setText("Hello Admin");
        jMenuBar1.add(jMenu1);

        members.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/members.png"))); // NOI18N
        members.setText("Members");

        add_member.setText("Add Member");
        add_member.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_memberMouseClicked(evt);
            }
        });
        add_member.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_memberActionPerformed(evt);
            }
        });
        members.add(add_member);

        delete_member.setText("Delete Member");
        members.add(delete_member);

        view_members.setText("View members");
        members.add(view_members);

        jMenuBar1.add(members);

        trainers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/members.png"))); // NOI18N
        trainers.setText("Trainers");

        add_trainer.setText("Add Trainer");
        add_trainer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_trainerActionPerformed(evt);
            }
        });
        trainers.add(add_trainer);

        delete_trainer.setText("Delete Trainer");
        delete_trainer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_trainerActionPerformed(evt);
            }
        });
        trainers.add(delete_trainer);

        view_trainers.setText("View Trainers");
        trainers.add(view_trainers);

        jMenuBar1.add(trainers);

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        logout.setText("logout");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        jMenuBar1.add(logout);

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        exit.setText("Exit");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        jMenuBar1.add(exit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_memberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_memberActionPerformed
        // TODO add your handling code here:
        new add_member().setVisible(true);
    }//GEN-LAST:event_add_memberActionPerformed

    private void add_trainerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_trainerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_trainerActionPerformed

    private void delete_trainerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_trainerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delete_trainerActionPerformed

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        new Login_form().setVisible(true);
    }//GEN-LAST:event_logoutMouseClicked

    private void add_memberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_memberMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_add_memberMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem add_member;
    private javax.swing.JMenuItem add_trainer;
    private javax.swing.JMenuItem delete_member;
    private javax.swing.JMenuItem delete_trainer;
    private javax.swing.JMenu exit;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JMenu logout;
    private javax.swing.JMenu members;
    private javax.swing.JMenu trainers;
    private javax.swing.JMenuItem view_members;
    private javax.swing.JMenuItem view_trainers;
    // End of variables declaration//GEN-END:variables
}
